---
- name: "Challenge answers"
  hosts: localhost

  tasks:

    - name: "test reachability"
      ping:

    - name: "find module"
      find:
        path: ~/Desktop/automation/ansible
        file_type: file